# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Circle CI Test
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      # Change this, as applicable to you      
      # Change this, as applicable to you
      # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      Tags: 
        - Key: Name 
          Value: Server1
      ImageId: 'ami-09e67e426f25ce0d7' 
      KeyName: !Ref ServerKeyPair
      InstanceType: t3.micro
  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      # Change this, as applicable to you      
      Tags: 
        - Key: Name 
          Value: Server2
      # Change this, as applicable to you
      # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      ImageId: 'ami-09e67e426f25ce0d7' 
      KeyName: !Ref ServerKeyPair
      InstanceType: t3.micro
